---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yaml
      skip: true

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    glauth_ui_delegate_to: "{{ ansible_host }}"
    glauth_ui_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/glauth-ui', true) }}/{{ glauth_ui_version }}"
  when:
    - glauth_ui_direct_download

- name: install dependency
  ansible.builtin.package:
    name: "{{ glauth_ui_requirements }}"
    state: present

- name: get latest release
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - glauth_ui_version == "latest"
  block:
    - name: get latest release
      delegate_to: localhost
      become: false
      run_once: true
      bodsch.scm.github_latest:
        project: yvesago
        repository: glauth-ui-light
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      register: _latest_release

    - name: re-define glauth_ui_version
      ansible.builtin.set_fact:
        glauth_ui_version: "{{ _latest_release.latest_release }}"

# - name: latest release
#   when:
#     - glauth_ui_version == "latest"
#   block:
#     - name: get latest release
#       delegate_to: localhost
#       become: false
#       run_once: true
#       ansible.builtin.uri:
#         url: "https://api.github.com/repos/glauth/glauth/releases/latest"
#         method: GET
#         return_content: true
#         status_code: 200
#         body_format: json
#         validate_certs: false
#         user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
#         password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
#       # no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
#       register: _latest_release
#       until: _latest_release.status == 200
#       retries: 5
#
#     - name: set glauth-ui version to {{ _latest_release.json.tag_name[1:] }}
#       ansible.builtin.set_fact:
#         glauth_ui_version: "{{ _latest_release.json.tag_name[1:] }}"

- name: detect our installation path '{{ glauth_ui_install_path | dirname }}'
  ansible.builtin.stat:
    path: "{{ glauth_ui_install_path | dirname }}"
    get_checksum: false
  register: stat_glauth_ui_path
  ignore_errors: true

- name: old installation
  when:
    - stat_glauth_ui_path is defined
    - stat_glauth_ui_path.stat is defined
    - stat_glauth_ui_path.stat.isdir is defined
    - not stat_glauth_ui_path.stat.isdir
  block:
    - name: stop old service
      ansible.builtin.service:
        name: glauth-ui
        state: stopped
        enabled: false
      notify:
        - daemon-reload

    - name: remove installed systemd unit
      ansible.builtin.file:
        state: absent
        path: /etc/systemd/system/glauth-ui-light.service
      when:
        - ansible_service_mgr | lower == "systemd"

    - name: remove installed glauth-ui
      ansible.builtin.file:
        state: absent
        path: "{{ stat_glauth_ui_path.stat.path }}"

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: detect installed glauth-ui binary
  ansible.builtin.stat:
    path: "{{ glauth_ui_install_path }}/glauth-ui"
  register: stat_glauth_ui_binary

- name: create download directory
  become: false
  delegate_to: "{{ glauth_ui_delegate_to }}"
  ansible.builtin.file:
    path: "{{ glauth_ui_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: user and group handling
  when:
    - glauth_ui_system_user != "root"
  block:
    - name: create glauth-ui group
      ansible.builtin.group:
        name: "{{ glauth_ui_system_group }}"
        state: present
        system: true

    - name: create glauth-ui user
      ansible.builtin.user:
        name: "{{ glauth_ui_system_user }}"
        groups: "{{ glauth_ui_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ glauth_ui_install_path }}"
    state: directory
    owner: "{{ glauth_ui_system_user }}"
    group: "{{ glauth_ui_system_group }}"
    mode: 0755

- name: create ansible local facts directory
  ansible.builtin.file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: merge glauth-ui configuration between defaults and custom
  ansible.builtin.set_fact:
    glauth_ui_config: "{{ glauth_ui_defaults_config | combine(glauth_ui_config, recursive=True) }}"
    glauth_ui_security: "{{ glauth_ui_defaults_security | combine(glauth_ui_security, recursive=True) }}"
    glauth_ui_ssl: "{{ glauth_ui_defaults_ssl | combine(glauth_ui_ssl, recursive=True) }}"
    glauth_ui_logs: "{{ glauth_ui_defaults_logs | combine(glauth_ui_logs, recursive=True) }}"
    glauth_ui_locale: "{{ glauth_ui_defaults_locale | combine(glauth_ui_locale, recursive=True) }}"
    glauth_ui_passpolicy: "{{ glauth_ui_defaults_passpolicy | combine(glauth_ui_passpolicy, recursive=True) }}"
    glauth_ui_cfg_users: "{{ glauth_ui_defaults_cfg_users | combine(glauth_ui_cfg_users, recursive=True) }}"
    glauth_ui_cfg_groups: "{{ glauth_ui_defaults_fg_groups | combine(glauth_ui_cfg_groups, recursive=True) }}"

...
