---

glauth_ui_config:
  debug: true
  tests: true
  listen:
    address: "0.0.0.0"

glauth_ui_security:
  trusted_proxies:
    - "127.0.0.1"
  csrf_random: "igIZiML6oBXl9lBcuqOCGyUHeuLqKGkj"

glauth_ui_cfg_users:
  start: 3000               # start with this uid number
  gid:
    admin: 3000             # members of this group are admins
    can_change_pass: 4000   # members of this group can change their password
    # use_otp: 5501           # members of this group use OTP

glauth_ui_cfg_groups:
  start: 3000

glauth_ui_passpolicy:
  min: 3
  max: 42
  # to be set to false when all passwords are bcrypt
  allow_reads_sha256: true
  # optional constraint. Between 40 and 120 for very high strength password
  entropy: 2

glauth_ui_locale:
  lang: "de"
  langs:
    - "en-US"
    - "de_DE"

...
