---

- name: restart glauth-ui
  become: true
  ansible.builtin.service:
    name: glauth-ui
    state: restarted

- name: reload glauth-ui
  become: true
  ansible.builtin.service:
    name: glauth-ui
    state: reloaded

- name: validate config  # noqa no-changed-when
  ansible.builtin.command: /bin/true

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
